[workspace]
resolver = "3"
members = [
  "./problems/median-of-sorted-arrays/",
  "./problems/palindromic-substring",
  "./problems/regular-expression-matching", "problems/p1545-find-kth-bit-in-nth-binary-string", "problems/spiral-matrix",
]

[profile.release]
debug = true

[alias]
flamegraph = "!cargo-flamegraph"
