[workspace]
resolver = "3"
members = [
  "./problems/median-of-sorted-arrays/",
  "./problems/palindromic-substring",
  "./problems/regular-expression-matching", "problems/p1382-balance-binary-search-tree", "problems/p1545-find-kth-bit-in-nth-binary-string", "problems/p3296-minimum-nmber-seconds-to-eat-mountain", "problems/p761-special-binary-strings", "problems/spiral-matrix",
]

[profile.release]
debug = true

[alias]
flamegraph = "!cargo-flamegraph"
